services:
  app:
    build:
      context: .
      target: runtime
    image: lucasfmp/restaurante-lucas-fernando:latest
    container_name: marmitatech-app
    ports:
      - "8089:3000"
    environment:
      DB_HOST: 54.89.88.5
      DB_USER: root
      DB_PASS: password
      DB_NAME: lfdb

networks:
  rede_alunos:
    external: true
