services:
  app:
    image: lucasfmp/restaurante-lucas-fernando:staging
    container_name: restaurante-lucas-fernando
    ports:
      - "8089:3000"
    environment:
      DB_HOST: dbcentral
      DB_USER: root
      DB_PASS: password
      DB_NAME: lfdb
    networks:
      - rede_alunos

networks:
  rede_alunos:
    external: true
